####### IDEAS AND PLANS TO COMPNUTATIONAL APPROACH

# SENTIMENT FUNCTION

# Nature classifier: PRo-nature (positive/negative framing), other etc
# PYTHON SCRIPT FROM ECOLOGY PAPER

# BUT DO WE FOCUS ON EMOTIONS? FOR OUR TOPICS...

# Topic model emotions
# NEG: Topics - Anxiety (anticpation, sasdness). Disgust (disgust), Anger *Anger, frustration"
# POS: Biophilla (happines, nature), Trust/Alert,

# Build our own dictionaries or use existing...?

# MOST LIKELY BOTH, WE SHOULD AS CAREFULLY AS POSSIBLE ASSEMBLE OUR DICTIONARIES FOR THESE EMOTIONS STARTING WITH THE AMALGMATION OF THE EXISTING DICTIONARIES

# TEST, TRAIN AND DEPLOY MODEL


#### IDEAS ####
# WORKING WITH AN INDIVIDUAL RIVER GROUP AND LOCAL COUNCIL TO SHOW A QR CODE TO THE RIVERS HEALTH
# PUBLIC ENGAGEMENT WITH THE APPLICATION AND ENGAGEMENT WITH THE ECOLOGICAL DATA
